import type { ICrop } from '../types';

export const crops: ICrop[] = [
	{
		id: 1,
		name: 'Tomato',
		category: 'Vegetable',
		soil: 'Loamy, well-drained soil with a pH of 6.0-6.8',
		image: '/images/tomato.webp',
		varieties: ['Roma', 'Cherry', 'Beefsteak'],
		cultivationMethods: ['Organic', 'Hydroponics', 'Traditional'],
		harvestingTechniques: ['Manual picking', 'Mechanical harvest'],
		nutritionalValues: 'Rich in Vitamin C, Potassium, and Lycopene',
		potentialUses: ['Food (fresh, sauces, soups)', 'Medicinal (anti-inflammatory)', 'Cosmetic (skin care)'],
	},
	{
		id: 2,
		name: 'Wheat',
		category: 'Grain',
		soil: 'Sandy loam to clay loam, pH 6.0-7.0',
		image: '/images/wheat.webp',
		varieties: ['Hard Red Winter', 'Soft Red Winter', 'Durum'],
		cultivationMethods: ['Conventional', 'No-till'],
		harvestingTechniques: ['Mechanical harvesting', 'Manual reaping'],
		nutritionalValues: 'High in Carbohydrates, Protein, Fiber, B Vitamins',
		potentialUses: ['Food (bread, pasta)', 'Animal feed', 'Biofuel production'],
	},
	{
		id: 3,
		name: 'Apple',
		category: 'Fruit',
		soil: 'Well-drained loamy soil with a pH of 6.0-7.0',
		image: '/images/apple.webp',
		varieties: ['Fuji', 'Granny Smith', 'Gala'],
		cultivationMethods: ['Conventional', 'Organic'],
		harvestingTechniques: ['Manual picking'],
		nutritionalValues: 'Rich in Fiber, Vitamin C, and Antioxidants',
		potentialUses: ['Food (fresh, juice, pie)', 'Medicinal (digestive health)', 'Cosmetic (skin care)'],
	},
	{
		id: 4,
		name: 'Cucumber',
		category: 'Vegetable',
		soil: 'Sandy loam, pH 6.0-7.0, well-drained',
		image: '/images/cucumber.jpg',
		varieties: ['Slicing', 'Pickling', 'European'],
		cultivationMethods: ['Traditional', 'Hydroponics'],
		harvestingTechniques: ['Manual picking'],
		nutritionalValues: 'Low in Calories, Hydrating, Rich in Vitamin K',
		potentialUses: ['Food (salads, sandwiches)', 'Cosmetic (hydrating, anti-inflammatory)'],
	},
	{
		id: 5,
		name: 'Rice',
		category: 'Grain',
		soil: 'Flooded fields, loamy soil, pH 5.5-7.0',
		image: '/images/rice.jpg',
		varieties: ['Basmati', 'Jasmine', 'Arborio'],
		cultivationMethods: ['Traditional', 'Waterlogged (paddy fields)'],
		harvestingTechniques: ['Mechanical harvesting', 'Manual harvesting'],
		nutritionalValues: 'High in Carbohydrates, Low in Fat, Gluten-free',
		potentialUses: ['Food (rice dishes, rice flour)', 'Industrial (biofuel)', 'Animal feed'],
	},
	{
		id: 6,
		name: 'Banana',
		category: 'Fruit',
		soil: 'Loamy, rich in organic matter, pH 5.5-7.0',
		image: '/images/banana.webp',
		varieties: ['Cavendish', 'Red Banana', 'Plantain'],
		cultivationMethods: ['Conventional', 'Organic'],
		harvestingTechniques: ['Manual harvesting'],
		nutritionalValues: 'Rich in Potassium, Vitamin B6, and Dietary Fiber',
		potentialUses: ['Food (fresh, smoothies, desserts)', 'Medicinal (digestive health)', 'Cosmetic (skin care)'],
	},
	{
		id: 7,
		name: 'Potato',
		category: 'Vegetable',
		soil: 'Well-drained, loose soil with a pH of 5.5-6.5',
		image: '/images/potato.webp',
		varieties: ['Russet', 'Yukon Gold', 'Red Potato'],
		cultivationMethods: ['Traditional', 'Hydroponics'],
		harvestingTechniques: ['Manual harvesting', 'Mechanical harvesting'],
		nutritionalValues: 'Rich in Vitamin C, Potassium, and Carbohydrates',
		potentialUses: ['Food (baked, mashed, fries)', 'Animal feed', 'Starch production'],
	},
	{
		id: 8,
		name: 'Coffee',
		category: 'Cash Crop',
		soil: 'Well-drained, rich in organic matter, pH 6.0-6.5',
		image: '/images/coffee.jpg',
		varieties: ['Arabica', 'Robusta'],
		cultivationMethods: ['Traditional', 'Shade-grown'],
		harvestingTechniques: ['Manual picking'],
		nutritionalValues: 'Contains Caffeine, Antioxidants',
		potentialUses: ['Beverages (coffee)', 'Cosmetic (skin care)', 'Industrial (biofuel)'],
	},
	{
		id: 9,
		name: 'Cotton',
		category: 'Cash Crop',
		soil: 'Loamy, well-drained soil with a pH of 5.5-7.0',
		image: '/images/cotton.jpg',
		varieties: ['Upland Cotton', 'Pima Cotton'],
		cultivationMethods: ['Conventional', 'Organic'],
		harvestingTechniques: ['Mechanical harvesting', 'Manual harvesting'],
		nutritionalValues: 'High in Fiber',
		potentialUses: ['Textiles (clothing, fabrics)', 'Industrial (oil production)', 'Cosmetic (skin care)'],
	},
];
